# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gK2p5EeaPAV6wQ0Jqc8Mi1mHUn1WapWo
"""

# main.py


# ==========================================
# 1. Import Data
# ==========================================

from data import places


# ==========================================
# 2. Import Simulation Functions
# ==========================================

from simulation import (
    simulate_crowd,
    calculate_visitors,
    get_crowd_status
)


# ==========================================
# 3. Run Crowd Simulation
# ==========================================

places = simulate_crowd(places)


# ==========================================
# 4. Display Header
# ==========================================

print("\n")
print("=" * 70)
print("             EGYPT TOURISM CROWD SIMULATION")
print("=" * 70)


# ==========================================
# 5. Display All Tourist Places
# ==========================================

place_number = 1


for place, data in places.items():

    # Calculate current visitors
    visitors = calculate_visitors(
        data["capacity"],
        data["crowd"]
    )

    # Get crowd status
    status = get_crowd_status(
        data["crowd"]
    )

    print("\n")
    print("Place Number:", place_number)
    print("Place:", place)
    print("Latitude:", data["lat"])
    print("Longitude:", data["lon"])
    print("Capacity:", data["capacity"])
    print("Crowd:", str(data["crowd"]) + "%")
    print("Current Visitors:", visitors)
    print("Status:", status)

    print("-" * 70)

    place_number += 1


# ==========================================
# 6. Display Highly Crowded Places
# ==========================================

print("\n")
print("=" * 70)
print("              HIGHLY CROWDED PLACES")
print("=" * 70)


high_crowd_count = 0


for place, data in places.items():

    if data["crowd"] > 70:

        print(
            place,
            "->",
            str(data["crowd"]) + "%"
        )

        high_crowd_count += 1


# ==========================================
# 7. Display Number of Highly Crowded Places
# ==========================================

print("\nNumber of highly crowded places:", high_crowd_count)


# ==========================================
# 8. Finish
# ==========================================

print("\n")
print("=" * 70)
print("Simulation Finished!")
print("=" * 70)