# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gK2p5EeaPAV6wQ0Jqc8Mi1mHUn1WapWo
"""

# Dictionary containing all tourist places in Egypt
places = {

    # ==========================================
    # Cairo and Giza
    # ==========================================

    "Pyramids of Giza": {
        "lat": 29.9792,
        "lon": 31.1342,
        "capacity": 25000,   # official (plateau); 300/day inside Great Pyramid
        "crowd": 0,
        'image': ['NTI/Egypt earthquakes/framebird-converted/pyramids/All_Gizah_Pyramids.png', 'NTI/Egypt earthquakes/framebird-converted/pyramids/All_pyramids_of_Giza_panorama_2.png', 'NTI/Egypt earthquakes/framebird-converted/pyramids/Giza_Pyramids_Egypt_Camels_Desert_Landscape_Photo_by_Ludovic_Delot_Bravo.png', 'NTI/Egypt earthquakes/framebird-converted/pyramids/Giza,_Pyramids,_Pictures,_F._Bonfils,_photo_7_of_27_-_Archivio_fotografico_Museo_Egizio,_Turin_INV01_010.png' ,'NTI/Egypt earthquakes/framebird-converted/pyramids/Sphinx_and_pyramids_of_Giza_panorama.png']
    },

    "Khan El Khalili": {
        "lat": 30.0478,
        "lon": 31.2622,
        "capacity": 5000,   # estimated (bazaar flow)
        "crowd": 0,
        'image': ['NTI/Egypt earthquakes/framebird-converted/khan elkhalily/_ cαιrο.png','NTI/Egypt earthquakes/framebird-converted/khan elkhalily/📍khan al khalili, Egypt 🇪🇬.png','NTI/Egypt earthquakes/framebird-converted/khan elkhalily/khan el-khalili bazaar.png','NTI/Egypt earthquakes/framebird-converted/khan elkhalily/خان الخليلي ♥️   Khan khalili-Egypt.png']
    },

    "Egyptian Museum": {
        "lat": 30.0478,
        "lon": 31.2336,
        "capacity": 3500,   # official (museum statistics)
        "crowd": 0,
        'image': ['NTI/Egypt earthquakes/framebird-converted/grand musuem/Grand-Egyptian-Museum-1-scaled.png','NTI/Egypt earthquakes/framebird-converted/grand musuem/Grand Egyptian museum.png','NTI/Egypt earthquakes/framebird-converted/grand musuem/Grand Egyptian Museum Guide (2026)_ Explore Egypt\'s Newest Cultural Landmark.png','NTI/Egypt earthquakes/framebird-converted/grand musuem/Grand Egyptian Museum - Cairo.png','NTI/Egypt earthquakes/framebird-converted/grand musuem/download (1).png']
    },

    "Citadel of Cairo": {
        "lat": 30.0296,
        "lon": 31.2589,
        "capacity": 15000,   # estimated (large open fortress)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/cairo citadel/Cairo_Citadel_2026.png','NTI/Egypt earthquakes/framebird-converted/cairo citadel/Scenes_from_Cairo_Citadel_(59407).png','NTI/Egypt earthquakes/framebird-converted/cairo citadel/Scenes_from_Cairo_Citadel_(84895).png','NTI/Egypt earthquakes/framebird-converted/cairo citadel/Scenes_from_Cairo_Citadel_7.png']
    },

    "Cairo Tower": {
        "lat": 30.0459,
        "lon": 31.2243,
        "capacity": 2000,   # estimated (observation deck)
        "crowd": 0,
        'image': ['NTI/Egypt earthquakes/framebird-converted/cairo tower/نهر_النيل_وبرج_القاهرة.png','NTI/Egypt earthquakes/framebird-converted/cairo tower/Cairo,_Tower_of_Cairo,_Egypt,_Oct_2004.png','NTI/Egypt earthquakes/framebird-converted/cairo tower/Cairo,_Egypt_(1990284866).png','NTI/Egypt earthquakes/framebird-converted/cairo tower/Cairo_Tower_at_night_(187m._high)_(14613470840).png']
    },

    "Al-Azhar Park": {
        "lat": 30.0401,
        "lon": 31.2650,
        "capacity": 8000,   # estimated (open-air park)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/azhar park/Al-Azhar_Mosque_(8590203917).png','NTI/Egypt earthquakes/framebird-converted/azhar park/Al-Azhar_Mosque_(R_Prazeres_2019)_DSCF4364.png','NTI/Egypt earthquakes/framebird-converted/azhar park/Al-Azhar-Park_2016-03-28e.png','NTI/Egypt earthquakes/framebird-converted/azhar park/Azhar_park_-_panoramio_(1).png','NTI/Egypt earthquakes/framebird-converted/azhar park/Azhar_Park.png','NTI/Egypt earthquakes/framebird-converted/azhar park/El_azhar_park.png']
    },

    "Hanging Church": {
        "lat": 30.0056,
        "lon": 31.2306,
        "capacity": 1000,   # estimated (church interior)
        "crowd": 0,
        'image' : ['NTI/Egypt earthquakes/framebird-converted/hanging church/Hanging Church - Interior.png','NTI/Egypt earthquakes/framebird-converted/hanging church/The Hanging Church, Coptic Cairo, Egypt.png','NTI/Egypt earthquakes/framebird-converted/hanging church/Egypt Christian church.png']
    },

    "Abdeen Palace": {
        "lat": 30.0419,
        "lon": 31.2486,
        "capacity": 2000,   # estimated (palace grounds)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/abdeen palace/Abdeen_Palace.png','NTI/Egypt earthquakes/framebird-converted/abdeen palace/Abdeen_Palace_Cairo_(52891275732).png','NTI/Egypt earthquakes/framebird-converted/abdeen palace/Abdeen_Palace_Cairo_(52886181378).png','NTI/Egypt earthquakes/framebird-converted/abdeen palace/Abdeen_Palace_Cairo_(52892014274).png','NTI/Egypt earthquakes/framebird-converted/abdeen palace/ركن_الشاي_بقصر_عابدين.png']
    },

    "Manial Palace": {
        "lat": 30.0260,
        "lon": 31.2235,
        "capacity": 1500,   # estimated (museum complex)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/Al Manial Palace Egypt.png']
    },

    "Baron Palace": {
        "lat": 30.0877,
        "lon": 31.3289,
        "capacity": 1800,   # estimated (heritage site)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/Baron palace/The_Baron_Palace.png','NTI/Egypt earthquakes/framebird-converted/Baron palace/Baron_Empain_Palace_Interior_87.png','NTI/Egypt earthquakes/framebird-converted/Baron palace/Baron_Empain_Palace_Interior_79.png','NTI/Egypt earthquakes/framebird-converted/Baron palace/Baron_Empain_Palace_Interior_88.png','NTI/Egypt earthquakes/framebird-converted/Baron palace/Baron_Empain_Palace_Interior_89.png']
    },

    "National Museum of Egyptian Civilization": {
        "lat": 30.0107,
        "lon": 31.2480,
        "capacity": 5000,   # official (museum data)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/national museum/National Museum of Egyptian Civilization Guided Tour.png','NTI/Egypt earthquakes/framebird-converted/national museum/National Museum Of Egyptian Civilization, Cairo, Egypt (1).png','NTI/Egypt earthquakes/framebird-converted/national museum/National Museum Of Egyptian Civilization, Cairo, Egypt.png','NTI/Egypt earthquakes/framebird-converted/national museum/National Museum of Egyptian Civilization.png']
    },

    "Museum of Islamic Art": {
        "lat": 30.0444,
        "lon": 31.2467,
        "capacity": 2000,   # estimated (museum size)
        "crowd": 0,
        'image': ['NTI/Egypt earthquakes/framebird-converted/islamic art musuem/Museum of Islamic Art - DOHA _ QATAR 📷zenabaroudi.png', 'NTI/Egypt earthquakes/framebird-converted/islamic art musuem/museum of islamic art (1).png', 'NTI/Egypt earthquakes/framebird-converted/islamic art musuem/Museum of Islamic Art Qatar.png', 'NTI/Egypt earthquakes/framebird-converted/islamic art musuem/Museum of Islamic art.png']
    },

    "Salah El-Din Citadel": {
        "lat": 30.0296,
        "lon": 31.2589,
        "capacity": 15000,   # estimated (same as Citadel of Cairo)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/salah aldin citadel/Citadel -of-Salah-El Din.png', 'NTI/Egypt earthquakes/framebird-converted/salah aldin citadel/Citadel of saladin Egypt.png' ,'NTI/Egypt earthquakes/framebird-converted/salah aldin citadel/Epic shots of Saladin Citadel.png' ,'NTI/Egypt earthquakes/framebird-converted/salah aldin citadel/Flickr_-_HuTect_ShOts_-_Citadel_of_Salah_El.Din_and_Masjid_Muhammad_Ali_قلعة_صلاح_الدين_الأيوبي_ومسجد_محمد_علي_-_Cairo_-_Egypt_-_17_04_2010_(4).png', 'NTI/Egypt earthquakes/framebird-converted/salah aldin citadel/Salaudin Citadel.png']
    },

    # ==========================================
    # Alexandria
    # ==========================================

    "Bibliotheca Alexandrina": {
        "lat": 31.2089,
        "lon": 29.9092,
        "capacity": 8000,   # official (library data)
        "crowd": 0,
        'image': ['NTI/Egypt earthquakes/framebird-converted/bib alex/Bibliotheca_Alexandrina_(2007-05-028).png','NTI/Egypt earthquakes/framebird-converted/bib alex/Bibliotheca_Alexandrina_(Alexandrie_bibliothèque).png','NTI/Egypt earthquakes/framebird-converted/bib alex/Bibliotheca_Alexandrina_06.png','NTI/Egypt earthquakes/framebird-converted/bib alex/Bibliotheca_Alexandrina_34.png','NTI/Egypt earthquakes/framebird-converted/bib alex/Coast_of_Alexandria,_A_view_From_Bibliotheca_Alexandrina,_Egypt.png']
    },

    "Qaitbay Citadel": {
        "lat": 31.2135,
        "lon": 29.8856,
        "capacity": 5000,   # estimated (fortress grounds)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/Qaitbay citadel/Citadel of Qaitbay.png' ,'NTI/Egypt earthquakes/framebird-converted/Qaitbay citadel/Egypt _ Alexandria 🇪🇬.png' ,'NTI/Egypt earthquakes/framebird-converted/Qaitbay citadel/Quaitbay Citadel.png']
    },

    "Catacombs of Kom El Shoqafa": {
        "lat": 31.1786,
        "lon": 29.8925,
        "capacity": 1000,   # estimated (underground tombs)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/catacombs of kom el shoqafa/113KOM_EL_SHOQAFA_CATACOMBS.png', 'NTI/Egypt earthquakes/framebird-converted/catacombs of kom el shoqafa/Catacombs_of_Kom_al_Shugafa_4.png', 'NTI/Egypt earthquakes/framebird-converted/catacombs of kom el shoqafa/Catacombs_of_Kom_El_Shoqafa,_Alexandria,_Egypt.png', 'NTI/Egypt earthquakes/framebird-converted/catacombs of kom el shoqafa/The_Tomb_from_Tigrane_Pasha_Street,_Catacombs_of_Kom_El_Shoqafa,_Alexandria,_Egypt.png']
    },

    "Pompey's Pillar": {
        "lat": 31.1824,
        "lon": 29.8968,
        "capacity": 2000,   # estimated (open-air site)
        "crowd": 0,
        'image' :['NTI/Egypt earthquakes/framebird-converted/pombay pillars/Egypt Travel Pro.png','NTI/Egypt earthquakes/framebird-converted/pombay pillars/Icezen - Home Improvement, Real Estate And The Lifestyle Blog.png','NTI/Egypt earthquakes/framebird-converted/pombay pillars/pompey\'s pillar،Alexandra, Egypt (1).png', 'NTI/Egypt earthquakes/framebird-converted/pombay pillars/pompey\'s pillar،Alexandra, Egypt.png']
    },

    "Roman Amphitheatre": {
        "lat": 31.1914,
        "lon": 29.9027,
        "capacity": 1500,   # estimated (heritage site)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/Roman amphitheater/Roman amphitheater (1).pn', 'NTI/Egypt earthquakes/framebird-converted/Roman amphitheater/Roman amphitheater.png','NTI/Egypt earthquakes/framebird-converted/Roman amphitheater/Roman Amphitheatre of Kom el-Dikka.png']
    },

    "Alexandria National Museum": {
        "lat": 31.1975,
        "lon": 29.9142,
        "capacity": 2000,   # estimated (museum size)
        "crowd": 0,
        'image': ["NTI/Egypt earthquakes/framebird-converted/alex museum/Alexandria_National_Museum10.png",'NTI/Egypt earthquakes/framebird-converted/alex museum/EWUG_visit_to_Alexandria_National_Museum,_April_2025_-_007.png','NTI/Egypt earthquakes/framebird-converted/alex museum/Musee_national_-_alexandrie_facade_vue_large.png','NTI/Egypt earthquakes/framebird-converted/alex museum/Explore The Coptic Museum - المتحف القبطي in 3D.png']
    },

    "Stanley Bridge": {
        "lat": 31.2380,
        "lon": 29.9460,
        "capacity": 5000,   # estimated (public bridge)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/stanlei bridge/Bridge ( Alexandria ).png', 'NTI/Egypt earthquakes/framebird-converted/stanlei bridge/download (8).png' ,'NTI/Egypt earthquakes/framebird-converted/stanlei bridge/download (9).png' ,'NTI/Egypt earthquakes/framebird-converted/stanlei bridge/Stanley Bridge, Alexandria, Egito.png']
    },

    "Alexandria Corniche": {
        "lat": 31.2001,
        "lon": 29.9187,
        "capacity": 10000,   # estimated (public promenade)
        "crowd": 0,
        'image':["NTI/Egypt earthquakes/framebird-converted/alex corniche/Alexandria Travel Guide_ History, Population, Sights & Tips.png",'NTI/Egypt earthquakes/framebird-converted/alex corniche/Alexandria_Corniche_,_photo_by_Hatem_Moushir_26.png','NTI/Egypt earthquakes/framebird-converted/alex corniche/Corniche_of_Alexandria.png','NTI/Egypt earthquakes/framebird-converted/alex corniche/Egypt,_Alexandria,_The_Corniche_of_Alexandria,_Mediterranean_Sea.png']
    },

    # ==========================================
    # Luxor
    # ==========================================

    "Luxor Temple": {
        "lat": 25.6995,
        "lon": 32.6396,
        "capacity": 3000,   # estimated (tourism board)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/luxor temple/Egyptology - Luxor temple.png', 'NTI/Egypt earthquakes/framebird-converted/luxor temple/Luxor egypt.png', 'NTI/Egypt earthquakes/framebird-converted/luxor temple/Luxor Temple_ A Journey Through Ancient Egypt.png']
    },

    "Karnak Temple": {
        "lat": 25.7188,
        "lon": 32.6573,
        "capacity": 20000,   # estimated (UNESCO site mgmt.)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/karnak temple/Karnak Temple Complex.png','NTI/Egypt earthquakes/framebird-converted/karnak temple/Karnak Temple, Egypt.png','NTI/Egypt earthquakes/framebird-converted/karnak temple/Karnak Temple, Luxor (1).png','NTI/Egypt earthquakes/framebird-converted/karnak temple/Karnak Temple.png']
    },

    "Valley of the Kings": {
        "lat": 25.7402,
        "lon": 32.6014,
        "capacity": 8000,   # estimated (UNESCO/tourism board)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/valley of kings/Valley Of The Kings - Tombs, location, and facts - Your ultimate Guide.png', 'NTI/Egypt earthquakes/framebird-converted/valley of kings/Valley of the Kings, Luxor _ Family Egypt Tour.png' ,'NTI/Egypt earthquakes/framebird-converted/valley of kings/The Valley of the Kings_ Egypt’s Buried Heritage.png']
    },

    "Valley of the Queens": {
        "lat": 25.7297,
        "lon": 32.6036,
        "capacity": 3000,   # estimated (smaller valley)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/valley of queens/The Valley of the Queens, Egypt_ A Visitor’s Guide — The Discoveries Of.png', 'NTI/Egypt earthquakes/framebird-converted/valley of queens/Valley of queens.png', 'NTI/Egypt earthquakes/framebird-converted/valley of queens/Valley of the Queens.png']
    },

    "Hatshepsut Temple": {
        "lat": 25.7382,
        "lon": 32.6063,
        "capacity": 4000,   # estimated (UNESCO/tourism board)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/hatshipsut/Hatshpsut Temple at Luxor photo courtesy of Mahmoud Younes.png','NTI/Egypt earthquakes/framebird-converted/hatshipsut/Temple of Hatshepsut_ Queen Who Became Pharaoh.png', 'NTI/Egypt earthquakes/framebird-converted/hatshipsut/Templo de Hatshepsut.png', 'NTI/Egypt earthquakes/framebird-converted/hatshipsut/The Temple of Queen Hatshepsut - Sparkles and___.png']
    },

    "Luxor Museum": {
        "lat": 25.7054,
        "lon": 32.6455,
        "capacity": 1500,   # estimated (museum size)
        "crowd": 0,
        'image' :['NTI/Egypt earthquakes/framebird-converted/luxor museum/Luksor Tapınağı_   📍Mısır_.png','NTI/Egypt earthquakes/framebird-converted/luxor museum/Luxor Museum & Mummification Museum.png', 'NTI/Egypt earthquakes/framebird-converted/luxor museum/Luxor Museum_ Top 10 Must-See Treasures.png' ,'NTI/Egypt earthquakes/framebird-converted/luxor museum/Luxor Museum.png']
    },

# ==========================================
# Aswan
# ==========================================

    "Philae Temple": {
        "lat": 24.0257,
        "lon": 32.8840,
        "capacity": 6000,   # estimated (ferry access limits)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/phiala temple/Philae temple - Egypt.png', 'NTI/Egypt earthquakes/framebird-converted/phiala temple/Philae Temple in Egypt.png', 'NTI/Egypt earthquakes/framebird-converted/phiala temple/The Philae Temple.png']
    },

    "Nubian Museum": {
        "lat": 24.0780,
        "lon": 32.8884,
        "capacity": 2000,   # estimated (museum size)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/nubian museum/Nubia Museum in Aswan, Egypt - Travel To Eat by Kurt Buzard MD.png', 'NTI/Egypt earthquakes/framebird-converted/nubian museum/Nubian Musuem.png' ,'NTI/Egypt earthquakes/framebird-converted/nubian museum/The Nubian Museum.png']
    },

    "Unfinished Obelisk": {
        "lat": 24.0775,
        "lon": 32.8981,
        "capacity": 1500,   # estimated (heritage site)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/Victory Obelisk/The Hatshepsut Obelisk - Karnak.png', 'NTI/Egypt earthquakes/framebird-converted/Victory Obelisk/The Victory Obelisk.png', 'NTI/Egypt earthquakes/framebird-converted/Victory Obelisk/Why Did the Sun Return to This Obelisk Every Morning_.png']
    },


    "Aswan High Dam": {
        "lat": 23.9700,
        "lon": 32.8778,
        "capacity": 5000,   # estimated (engineering site)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/high dam/Aswan_High_Dam_(2007-05-706).png', 'NTI/Egypt earthquakes/framebird-converted/high dam/Aswan_High_Dam_panorama_looking_downstream.png', 'NTI/Egypt earthquakes/framebird-converted/high dam/Aswan_High_Dam-1.png', 'NTI/Egypt earthquakes/framebird-converted/high dam/By_ovedc_-_Aswan_High_Dam_-_09.png']
    },

    "Nubian Village": {
        "lat": 24.0950,
        "lon": 32.8870,
        "capacity": 3000,   # estimated (community tourism)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/Nubian village/📍 Nubian village in Aswan Egypt 🇪🇬.png','NTI/Egypt earthquakes/framebird-converted/Nubian village/Nubian village - Egypt 🇪🇬🇻🇨 (1).png', 'NTI/Egypt earthquakes/framebird-converted/Nubian village/Nubian village - Egypt 🇪🇬🇻🇨.png', 'NTI/Egypt earthquakes/framebird-converted/Nubian village/Nubian village.png']
    },

# ==========================================
# Other Egyptian Tourist Attractions
# ==========================================

    "Abydos Temple": {
        "lat": 26.1858,
        "lon": 31.9190,
        "capacity": 3000,   # estimated (temple complex)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/abydos/Temple_of_Seti_I,_Columns,_Abydos,_Egypt.png', 'NTI/Egypt earthquakes/framebird-converted/abydos/960px-Osireion_at_Abydos.png', 'NTI/Egypt earthquakes/framebird-converted/abydos/960px-GD-EG-Abydos001.png', 'NTI/Egypt earthquakes/framebird-converted/abydos/Temple_of_Seti_I,_Interior,_Abydos,_Egypt.png']
    },

    "Siwa Oasis": {
        "lat": 29.2032,
        "lon": 25.5195,
        "capacity": 5000,   # estimated (open-air oasis)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/siwa/Cleopatra eye of siwa 👁️.png','NTI/Egypt earthquakes/framebird-converted/siwa/Discover Siwa Oasis In Egypt (2026)_ A Practical,___.png','NTI/Egypt earthquakes/framebird-converted/siwa/download (7).png','NTI/Egypt earthquakes/framebird-converted/siwa/Egypt Museum.png','NTI/Egypt earthquakes/framebird-converted/siwa/📍cleopatra spring, siwa oasis.png']
    },


    "White Desert": {
        "lat": 27.3080,
        "lon": 28.2010,
        "capacity": 4000,   # estimated (open-air desert park)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/white desert/White Desert - Part 2.png','NTI/Egypt earthquakes/framebird-converted/white desert/white desert in egypt.png','NTI/Egypt earthquakes/framebird-converted/white desert/Desert Mountent.png']
    },

    "Black Desert": {
        "lat": 28.3500,
        "lon": 28.8500,
        "capacity": 3000,   # estimated (open-air desert park)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/black desert/Black_Desert,_Egypt_10.png', 'NTI/Egypt earthquakes/framebird-converted/black desert/BlackDesertGebelMarsus.png', 'NTI/Egypt earthquakes/framebird-converted/black desert/Black-desert-egypt_cropped.png', 'NTI/Egypt earthquakes/framebird-converted/black desert/Black_Desert_in_Bahariya_Oasis.png']
    },

    "Wadi El Hitan": {
        "lat": 29.2730,
        "lon": 30.0510,
        "capacity": 2000,   # estimated (UNESCO fossil site)
        "crowd": 0,
        "image": ['NTI/Egypt earthquakes/framebird-converted/wadi Elhitan/Wadi Al-Hitan (Whale Valley).png', 'NTI/Egypt earthquakes/framebird-converted/wadi Elhitan/WADI Elhitan.png', 'NTI/Egypt earthquakes/framebird-converted/wadi Elhitan/Wadi-Al-Hitan (walvisvallei), Fayoem.png', 'NTI/Egypt earthquakes/framebird-converted/wadi Elhitan/Whale Valley_ The whale graveyard in the Sahara desert that shows they once had feet and toes.png']
    },

    "Ras Mohammed National Park": {
        "lat": 27.7300,
        "lon": 34.2500,
        "capacity": 10000,   # estimated (marine park)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/ras mohamed/11_10_2020 Ras Mohammed National Park_ Snorkeling Trip.png', 'NTI/Egypt earthquakes/framebird-converted/ras mohamed/Ras Mohammad National Park.png', 'NTI/Egypt earthquakes/framebird-converted/ras mohamed/Ras Mohammed National Park.png', 'NTI/Egypt earthquakes/framebird-converted/ras mohamed/Ras Mohammed.png']
    },

    "Naama Bay": {
        "lat": 27.9158,
        "lon": 34.3299,
        "capacity": 8000,   # estimated (beach resort)
        "crowd": 0,
        'image':['NTI/Egypt earthquakes/framebird-converted/naama pay/download (3).png', 'NTI/Egypt earthquakes/framebird-converted/naama pay/Naama Bay Sunset Magic in Sharm El Sheikh,.png', 'NTI/Egypt earthquakes/framebird-converted/naama pay/Nama bay Egypt.png']
    },

# ==========================================
# Additional major sites (lust).
# These entries were missing from data.py but each has a photo mapping in
# lib/data/place_images.dart, so they are added to keep the datasets in sync.
# ==========================================

    "Abu Simbel Temples": {
        "lat": 22.3364,
        "lon": 31.6258,
        "capacity": 8000,   # estimated (UNESCO site, visitor quotas)
        "crowd": 0,
        'image': []
    },

    "Al-Azhar Mosque": {
        "lat": 30.0459,
        "lon": 31.2625,
        "capacity": 5000,   # estimated (mosque & grounds)
        "crowd": 0,
        'image': []
    },

    "Cleopatra's Spring": {
        "lat": 29.2039,
        "lon": 25.5310,
        "capacity": 1500,   # estimated (Siwa hot spring)
        "crowd": 0,
        'image': []
    },

    "Colossi of Memnon": {
        "lat": 25.7206,
        "lon": 32.6106,
        "capacity": 2000,   # estimated (open-air Theban site)
        "crowd": 0,
        'image': []
    },

    "Coptic Museum": {
        "lat": 30.0061,
        "lon": 31.2307,
        "capacity": 1200,   # estimated (museum size)
        "crowd": 0,
        'image': []
    },

    "Dahab Blue Hole": {
        "lat": 28.5725,
        "lon": 34.5361,
        "capacity": 2500,   # estimated (diving site)
        "crowd": 0,
        'image': []
    },

    "Dendera Temple": {
        "lat": 26.1417,
        "lon": 32.6700,
        "capacity": 4000,   # estimated (temple complex)
        "crowd": 0,
        'image': []
    },

    "El Alamein Military Museum": {
        "lat": 30.8278,
        "lon": 28.9550,
        "capacity": 2000,   # estimated (museum size)
        "crowd": 0,
        'image': []
    },

    "Elephantine Island": {
        "lat": 24.1114,
        "lon": 32.8893,
        "capacity": 2500,   # estimated (island heritage site)
        "crowd": 0,
        'image': []
    },

    "Giftun Island": {
        "lat": 27.1700,
        "lon": 33.8500,
        "capacity": 6000,   # estimated (marine park / boat visitors)
        "crowd": 0,
        'image': []
    },

    "Medinet Habu": {
        "lat": 25.7196,
        "lon": 32.6011,
        "capacity": 3000,   # estimated (temple complex)
        "crowd": 0,
        'image': []
    },

    "Montaza Palace": {
        "lat": 31.2417,
        "lon": 30.0086,
        "capacity": 4000,   # estimated (palace gardens)
        "crowd": 0,
        'image': []
    },

    "Royal Jewelry Museum": {
        "lat": 31.2105,
        "lon": 29.9079,
        "capacity": 1200,   # estimated (museum size)
        "crowd": 0,
        'image': []
    },

    "St. Catherine Monastery": {
        "lat": 28.5562,
        "lon": 33.9762,
        "capacity": 2000,   # estimated (heritage monastery)
        "crowd": 0,
        'image': []
    },

}
important_places = {
    "Pyramids of Giza"  :{'coords': (29.9792,30.4342), 'image' : 'NTI/Egypt earthquakes/framebird-converted/pyramids/All_Gizah_Pyramids.png'},
    "Cairo Tower"       :{'coords' : (30.0459, 31.4743), 'image' : 'NTI/Egypt earthquakes/framebird-converted/cairo tower/Cairo,_Tower_of_Cairo,_Egypt,_Oct_2004.png'},
    "Egyptian Museum"   : {'coords' : (29.4878, 30.8936),'image' : 'NTI/Egypt earthquakes/framebird-converted/grand musuem/Grand-Egyptian-Museum-1-scaled.png'},
    "Bibliotheca Alexandrina": {'coords' : (31.1989, 29.2092),'image' : 'NTI/Egypt earthquakes/framebird-converted/bib alex/Coast_of_Alexandria,_A_view_From_Bibliotheca_Alexandrina,_Egypt.png'},
    "Qaitbay Citadel"   : {'coords' : (30.999, 30.0856),'image' : 'NTI/Egypt earthquakes/framebird-converted/Qaitbay citadel/Egypt _ Alexandria 🇪🇬.png'},
    "Luxor Temple"      : {'coords' : (25.6995, 32.6396),'image' : 'NTI/Egypt earthquakes/framebird-converted/luxor temple/Luxur temple.png'},
    "Karnak Temple"     : {'coords' : (25.7188, 31.6573),'image' : 'NTI/Egypt earthquakes/framebird-converted/karnak temple/Karnak Temple, Egypt.png'},
    "Siwa Oasis"        : {'coords' : (29.2032, 27.5195),'image' : 'NTI/Egypt earthquakes/framebird-converted/siwa/download (7).png'},
    "Wadi El Hitan"     : {'coords' : (29.0730, 28.5510),'image' : 'NTI/Egypt earthquakes/framebird-converted/wadi Elhitan/Wadi Al-Hitan (Whale Valley).png'},
    "Ras Mohammed National Park": {'coords' : (27.8500, 34.120),'image' : 'NTI/Egypt earthquakes/framebird-converted/ras mohamed/11_10_2020 Ras Mohammed National Park_ Snorkeling Trip.png'},
    "Philae Temple"     : {'coords' : ( 24.0257, 33.090),'image' : 'NTI/Egypt earthquakes/framebird-converted/phiala temple/Philae Temple in Egypt.png'},
    "Nubian Museum"     : {'coords' : (24.1780, 32.4884),'image' : 'NTI/Egypt earthquakes/framebird-converted/nubian museum/The Nubian Museum.png'},
    "Hatshepsut Temple": {'coords' : (25.7382, 32.6063),'image' : 'NTI/Egypt earthquakes/framebird-converted/hatshipsut/Hatshpsut Temple at Luxor photo courtesy of Mahmoud Younes.png'},

}
egypt_cities = {
    "Cairo": (31.2333, 30.0444),           # Cairo Capital
    "Alexandria": (29.9245, 31.2058),      # Alexandria Capital
    "Giza": (30.4088, 30.0130),            # Giza Capital
    "Port Said": (32.2841, 31.2653),       # Port Said Capital
    "Suez": (32.5498, 29.9668),            # Suez Capital
    "Ismailia": (32.2673, 30.6043),        # Ismailia Capital
    "Damanhur": (30.4714, 31.0364),        # Beheira Capital
    "Kafr El Sheikh": (31.1113, 31.4107),  # Kafr El Sheikh Capital
    "Tanta": (31.0004, 30.7865),           # Gharbia Capital
    "Shibin El Kom": (31.0084, 30.5510),   # Monufia Capital
    "Banha": (31.1846, 30.4591),           # Qalyubia Capital
    "Mansoura": (31.3815, 31.0379),        # Dakahlia Capital
    "Damietta": (31.8144, 31.4175),        # Damietta Capital
    "Zagazig": (31.5167, 30.5833),         # Sharqia Capital
    "Fayoum": (30.8428, 29.3084),          # Faiyum Capital
    "Beni Suef": (31.1190, 29.0884),       # Beni Suef Capital
    "Minya": (30.7500, 28.1100),           # Minya Capital
    "Asyut": (31.1892, 27.1801),           # Asyut Capital
    "Sohag": (31.7000, 26.5500),           # Sohag Capital
    "Qena": (32.7260, 26.1660),            # Qena Capital
    "Luxor": (32.6396, 25.6872),           # Luxor Capital
    "Aswan": (32.8997, 24.0889),           # Aswan Capital
    "Mersa Matruh": (27.2373, 30.8525),    # Matrouh Capital
    "Kharga": (30.5550, 25.4476),          # New Valley Capital
    "Hurghada": (34.1300, 28.0900),        # Red Sea Capital
    "Arish": (33.8033, 31.1319),           # North Sinai Capital
    "El Tor": (33.6254, 28.2411)           # South Sinai Capital
    }

# cities info 
cities_info = {
    "Cairo": "Cairo is the vibrant capital of Egypt and the largest metropolitan area in Africa and the Arab world. Situated along the banks of the Nile River, it serves as the country's primary economic, political, and cultural hub. Known affectionately as 'The City of a Thousand Minarets' due to its stunning Islamic architecture, Cairo seamlessly blends ancient history—lying just miles from the iconic Giza Plateau and the Pyramids—with a bustling, fast-paced modern urban lifestyle.",
    "Alexandria": "Alexandria is Egypt's second-largest city and its principal seaport, stretching dynamically along the coast of the Mediterranean Sea. Founded in 331 BCE by Alexander the Great, it served as a legendary beacon of the ancient world, famous for the Pharos Lighthouse—one of the Seven Wonders of the Ancient World—and the Great Library of Alexandria. Today, it operates as a major industrial center, a bustling economic engine, and a popular cultural destination, seamlessly blending a breezy Mediterranean atmosphere with deep Greco-Roman historical roots.",
    "Giza": "Giza is Egypt's third-largest city, situated on the west bank of the Nile River directly opposite Cairo. It is globally famous as the home of the Giza Plateau, which hosts the iconic Great Pyramids, the Great Sphinx, and Khufu's Solar Boat, making it a monumental hub for world heritage and archaeology. Part of the Greater Cairo metropolis, Giza merges historical wonders with rapid modern expansion, housing major cultural institutions like the Grand Egyptian Museum (GEM) alongside vibrant commercial centers, academic institutions, and bustling urban districts.",
    "Port Said": "Port Said is a historic coastal city and a vital global shipping hub situated in northeastern Egypt along the Mediterranean Sea. Established in 1859 during the excavation of the Suez Canal, it sits at the northern entrance of this critical international waterway, making it a bustling economic engine for maritime trade. Known for its unique 19th-century cosmopolitan architecture, elevated boardwalks, and a duty-free commercial zone, Port Said serves as a gateway linking trade routes between Europe and Asia.",
    "Suez": "Suez is a strategic port city located in northeastern Egypt at the southern terminus of the Suez Canal, right along the coast of the Gulf of Suez. Emerging from ancient maritime trade routes, it underwent massive industrial expansion following the opening of the canal in 1869, transforming it into a critical global hub for international shipping, petroleum refining, and petrochemical manufacturing. The city plays a vital dual role as both an economic gateway linking the Red Sea to the Mediterranean and a foundational industrial pillar for modern Egypt.",
    "Ismailia": 'Ismailia is a charming and picturesque city in northeastern Egypt, known affectionately as "The City of Beauty and Enchantment." Founded in 1862 by Khedive Ismail during the construction of the Suez Canal, it serves as the administrative headquarters of the Suez Canal Authority. Strategically positioned on the west bank of the canal, midway between Port Said and Suez, it features a unique layout centered around Lake Timsah. Ismailia stands out for its quiet, orderly design, lush green gardens, tree-lined avenues, and beautiful 19th-century French-style colonial architecture.',
    "Damanhur": 'Beheira is an expansive, highly strategic coastal governorate located in northern Egypt within the western region of the Nile Delta. Its capital city is Damanhur, an ancient urban center whose roots stretch all the way back to the Old Kingdom of Egypt.Beheira holds monumental historical and cultural value: it is home to the historic port city of Rosetta (Rashid), where the legendary Rosetta Stone was discovered in 1799, unlocking the mystery of ancient Egyptian hieroglyphs.',
    "Kafr El Sheikh": "Kafr El Sheikh is a highly strategic coastal governorate located in the northern region of the Nile Delta, beautifully bounded by the Mediterranean Sea to the north and the Rosetta branch of the Nile River to the west. Its namesake capital city serves as a bustling commercial and academic hub for the region.Geographically, Kafr El Sheikh is unique because it surrounds the massive Lake Burullus, a globally protected wetland nature reserve that makes the region a primary hub for Egypt's fishing industry. Historically, it holds deep archaeological significance: it is home to the ancient city of Buto (modern-day Tell El Fara'in), which served as the legendary capital of Lower Egypt during the Predynastic era.",
    "Tanta": "Gharbia is a vibrant, landlocked governorate situated dead-center in the heart of the Nile Delta, with Tanta serving as its high-energy capital city. It functions as a critical economic and transport backbone for northern Egypt, perfectly bridging the commercial routes between Cairo and Alexandria. Renowned as the industrial powerhouse of the Delta, the region drives Egypt's textile economy through the massive manufacturing hubs of El Mahalla El Kubra, while seamlessly blending this industrial grit with rich agricultural heritage. Culturally, it is famous for the magnificent Sayed El-Badawi Mosque, which transforms the city annually into a dazzling cultural epicenter, hosting street festivals that draw millions of visitors from across the globe.",
    "Shibin El Kom": "Monufia is a highly populated and incredibly fertile governorate located in the southern apex of the Nile Delta, just north of Cairo, with Shibin El Kom serving as its vibrant capital city. Bounded beautifully by both the Rosetta and Damietta branches of the Nile, it is celebrated as the green heart of Egypt’s agricultural sector, leading the nation in the cultivation of premium crops, fruits, and vegetables. Beyond its farming legacy, Monufia holds an exceptionally prominent position in modern Egyptian history, famous for being the ancestral home and birthplace of several of the nation's presidents and influential political leaders. It functions as a bustling academic and development hub, blending its quiet, sprawling agricultural fields with top-tier universities and rapidly expanding industrial zones like Sadat City.",
    "Banha": 'QalyubiaQalyubia is a highly strategic governorate located at the southern tip of the Nile Delta, directly bordering Cairo to the south, with Banha serving as its vibrant capital city. Known famously as the "North Gateway to Cairo," it handles the massive daily flow of transport and commerce between the capital and the northern delta provinces. Qalyubia holds immense agricultural wealth, leading the nation in citrus fruit production, while simultaneously serving as a heavy industrial powerhouse centered around the manufacturing hubs of Shubra El Kheima. Culturally and logistically, it is bounded by the Nile River to the west, making it home to the historic Delta Barrages—a monumental 19th-century irrigation masterpiece that regulates the split of the Nile into its Rosetta and Damietta branches.',
    "Mansoura": " is a highly influential governorate located in the northeastern region of the Nile Delta, with Mansoura serving as its vibrant and culturally rich capital city. Bounded by the Damietta branch of the Nile River, it is known famously as 'The Bride of the Nile' due to its stunning waterfront views and exceptional architectural charm. Mansoura holds massive historical significance as the site of the Battle of Mansoura in 1250, where King Louis IX of France was captured during the Seventh Crusade, a victory preserved today at the historic Dar Ibn Luqman museum. Today, the city is a powerhouse for education and medicine, home to the world-renowned Mansoura University and premier specialized medical centers, blending its deep historical legacy with a high-energy, progressive urban lifestyle.",
    "Damietta": 'Damietta is a highly strategic coastal governorate located in northeastern Egypt, beautifully positioned where the Damietta branch of the Nile River meets the Mediterranean Sea. Its namesake capital, Damietta, is one of Egypt\'s oldest and most vital maritime hubs, famous for its historic seaport which anchors international trade routes and boasts a bustling, modern container terminal. Damietta holds immense economic weight as the nation\'s undisputed capital for furniture manufacturing, woodcraft, and leather works, driving a massive export market across the Middle East. Geographically unique, the governorate is home to Ras El Bar, a famous resort town built on the exact triangular peninsula where the fresh river waters of the Nile crash directly into the saltwater of the Mediterranean.',
    "Zagazig": 'Sharqia is a highly populated and economically vital governorate located in the eastern region of the Nile Delta, with Zagazig serving as its bustling and historically rich capital city. It holds immense agricultural weight, ranking as one of Egypt\'s top producers of critical crops like wheat, rice, and cotton, while simultaneously functioning as a modern industrial powerhouse through the massive manufacturing zones of 10th of Ramadan City. Sharqia has deep archaeological roots, hosting the ancient ruins of Bubastis (Tell Basta)—a major religious center dedicated to the cat goddess Bastet—and Tanis (San El-Hagar), a magnificent ancient capital city famed for its royal tombs and monumental obelisks. Culturally, the governorate is widely celebrated across the Arab world for its horse breeding heritage, hosting an annual international Arabian Horse Festival that attracts enthusiasts from around the globe.',
    "Fayoum": ' Faiyum is an ancient and geographically unique oasis governorate located just southwest of Cairo, with Fayoum City serving as its vibrant capital. Unlike typical desert oases, Fayoum is directly fed by the Nile River through a network of ancient canals called Bahr Yussef, making it an exceptionally fertile basin surrounded by rolling desert hills. It is world-renowned for its rich archaeological heritage, spanning prehistoric fossil sites like Wadi El Hitan (The Valley of Whales)—a UNESCO World Heritage site—to iconic Middle Kingdom pyramids and the famous Greco-Roman Fayoum Mummy Portraits. Today, the region blends its deep farming traditions with a thriving ecotourism industry, drawing visitors to the serene waters of Lake Qarun, the cascading waterfalls of Wadi El Rayan, and the artisan pottery village of Tunis.',
    "Beni Suef": "Beni Suef is a vital and rapidly growing governorate located in upper-middle Egypt along the west bank of the Nile River, with Beni Suef City serving as its vibrant capital. Functioning as a critical gateway connecting the northern Greater Cairo metropolis to the southern Upper Egypt region, it is a major transport and economic link. The governorate holds profound historical significance, highlighted by the majestic Pyramid of Meidum, a monumental archaeological treasure that marks the architectural transition from step pyramids to smooth-sided structures during the Old Kingdom. Today, Beni Suef combines its deep agricultural roots—cultivating essential crops like wheat and aromatic herbs—with an expanding industrial profile, featuring major cement manufacturing centers and new technological production zones that drive regional development.",
    "Minya": "Minya holds monumental archaeological value, housing Tell El-Amarna, the ancient capital from which Pharaoh Akhenaten and Queen Nefertiti launched their monotheistic sun-worship revolution. The region seamlessly blends its rich Pharaonic legacy—evident in the spectacular Middle Kingdom cliff tombs of Beni Hassan—with profound Greco-Roman and Coptic Christian history, featuring the historic Gabal El-Tayr Monastery, a sacred site commemorating the Holy Family's journey. Today, Minya balances its ancient heritage with a sprawling modern agricultural economy, leading the nation in high-quality soap, perfume, and sugar production.",
    "Asyut": "Asyut holds immense administrative and economic weight, functioning as the primary commercial, industrial, and transport gateway between the northern and southern halves of the Nile Valley. It is home to Asyut University, one of Egypt's largest and most prestigious academic and medical institutions outside of Cairo. Culturally, it holds profound significance across multiple eras: it houses the historic Deir El-Muharraq (Al-Muharraq Monastery), a sacred 4th-century monastery built on the exact site where the Holy Family is believed to have taken refuge for over six months during their biblical journey through Egypt. Logistically, the governorate is anchored by the historic Asyut Barrage, a masterfully engineered 19th-century Nile regulator that anchors the region's massive agricultural irrigation network.",
    "Sohag": "Sohag holds immense archaeological and spiritual weight, serving as a monumental bridge between ancient Pharaonic history and early Christian heritage. It is home to Abydos, one of the most sacred ancient Egyptian cities, which houses the spectacular Temple of Seti I and the legendary Seti I King List. The governorate is also globally renowned for its early Christian architecture, hosting the White Monastery (Deir El-Abiad) and the Red Monastery (Deir El-Ahmar), two of the most architecturally unique and beautifully preserved 5th-century Coptic Christian monastic complexes in existence. Today, Sohag merges this deep heritage with a bustling modern economy, anchored by Sohag University and a sprawling agricultural sector that leads the region in sugarcane and textile weaving production.",
    "Qena": "Geographically, the governorate is anchored by the Qena Bend, the sharpest and most dramatic curve in the entire path of the Nile River, which forces the waterway to loop deeply westward before continuing north. Qena holds monumental archaeological value, most famously hosting the Dendera Temple Complex, a beautifully preserved ancient Egyptian site dedicated to the goddess Hathor that features pristine, richly colored astronomical ceilings and relief carvings. Today, Qena balances its deep ancient heritage with a vital modern economy, serving as a bustling commercial gateway to the Red Sea via the Safaga desert highway, a prominent academic hub through South Valley University, and a leading agricultural center for Egypt's sugarcane cultivation and pottery production.",
    "Luxor": 'Known antiquity as Thebes, the ancient capital of the New Kingdom, Luxor is frequently described as the "world\'s greatest open-air museum" due to its unparalleled concentration of monumental ruins. The city is seamlessly divided by the Nile into two distinct archeological zones: the East Bank, which hosts vibrant modern life alongside the colossal Karnak and Luxor Temples, and the West Bank, a sacred necropolis housing the Valley of the Kings, the Valley of the Queens, and the mortuary temple of Hatshepsut. Today, Luxor beautifully blends this monumental Pharaonic heritage with a bustling international tourism economy, welcoming millions of global travelers who explore its timeless landscape by foot, Nile feluccas, and hot-air balloons.',
    "Aswan": 'wan is a highly prominent and breathtakingly scenic governorate located in southern Upper Egypt at the first cataract of the Nile River, with Aswan City serving as its vibrant capital.Functioning as Egypt\'s historic southern frontier gateway to Africa, Aswan holds massive strategic, economic, and engineering weight. It is globally renowned for the Aswan High Dam, a monumental 20th-century engineering masterpiece that regulates the Nile\'s annual floods and created Lake Nasser, one of the largest man-made reservoirs on Earth. Rich in ancient history, the governorate hosts spectacular archaeological treasures like the Philae Temple Complex—dedicated to the goddess Isis—and serves as the launching point for travelers journeying south to the colossal temples of Abu Simbel.',
    "Mersa Matruh": 'Matrouh is world-famous for its pristine, crystal-clear turquoise waters and soft white sands, making it an extraordinarily popular summer resort destination for beaches like Agiba and Cleopatra\'s Beach. Deep within its vast southern desert territory lies the legendary Siwa Oasis, a culturally distinct paradise famous for its olive and date groves, natural hot springs, the historic fortress of Shali, and the ancient Oracle Temple of Amun, where Alexander the Great was famously declared a pharaoh. Historically, Matrouh also marks a vital turning point of World War II, housing the town of El Alamein, a major battleground commemorated today by historic war cemeteries and a military museum.',
    "Kharga": "New Valley (El Wadi El Gedid) is Egypt's largest governorate by geographic size, occupying roughly %44 of the country's total land area in the vast southwestern expanse of the Western Desert, with Kharga serving as its vibrant capital city.Surrounded by massive desert terrain, New Valley is a sprawling network of ancient, fertile oases—primarily Kharga, Dakhla, and Farafra—that have been sustained for millennia by massive underground artesian aquifers. The governorate holds immense archaeological and natural heritage values; it hosts Pharaonic and Greco-Roman treasures like the Temple of Hibis and the early Christian cemetery of Al-Bagawat, alongside spectacular geographical formations like the White Desert National Park, famed for its wind-carved, chalk-white rock structures. Today, New Valley is the focal point of Egypt's major reclamation and development initiatives, transforming barren desert tracts into massive agricultural centers for date palm cultivation, wheat production, and phosphate mining.",
    "Hurghada": "Originally a small, quiet fishing village, Hurghada underwent massive transformation in the late 20th century to become one of the premier beach resort destinations in the world. It serves as a bustling hub for international tourism, famous for its year-round sunshine, vibrant marine nightlife, and spectacular luxury resorts. Geographically, it is a world-class gateway to the Red Sea's pristine marine environments, offering unparalleled access to stunning coral reefs and crystal-clear turquoise waters that make it a top destination for scuba diving, snorkeling, and windsurfing. The city perfectly bridges this coastal maritime economy with the sprawling Eastern Desert, hosting adventurous desert safaris and linking trade routes via the Qena-Safaga highway.",
    "Arish": "North Sinai is a strategically vital and historically rich frontier governorate located in northeastern Egypt, with Arish serving as its coastal capital city.Situated on the Mediterranean coast of the Sinai Peninsula, Arish is renowned for its sweeping beaches lined with palm trees, historically nicknamed the 'City of Palms'. The governorate functions as Egypt's eastern gateway, straddling the ancient Via Maris—one of the oldest trade and military routes in human history connecting Egypt with the Levant and Mesopotamia. Economically, the region relies on its Mediterranean fishing ports, olive and fruit groves, salt extraction industries, and its critical position for regional trade. It seamlessly blends a unique Bedouin cultural heritage with deep geopolitical and historical significance.",
    "El Tor": "South Sinai is a highly strategic frontier governorate occupying the southern half of the Sinai Peninsula, with El Tor (Tur Sinai) serving as its historic and administrative capital city. El Tor is the oldest continuously inhabited city in the governorate, deriving its name from Jabal Al Tor, the holy mountain range where the prophet Moses is traditionally believed to have received the Tablets of the Law. Nestled along the eastern coast of the Gulf of Suez, the city holds a profound place in maritime and religious history. It is widely celebrated for Hammam Musa (The Baths of Moses), natural artesian thermal springs rich in sulfur used for therapeutic relaxation and skin treatments. Today, El Tor perfectly balances its administrative importance with specialized ecotourism, operating as a prime global destination for windsurfing due to its pristine, isolated beaches and exceptional year-round wind conditions",
}

# Earthquake event definitions (served to the Flutter app via /api/earthquake-events)
earthquake_events = [
    {
        "id": "cairo",
        "label": "Cairo 1992",
        "magnitude": 5.8,
        # Cairo city coords (used as epicenter in original)
        "epicenter_lon": 31.2333,
        "epicenter_lat": 30.0444,
        "story": "On October 12, 1992, at 3:09 PM local time, a 5.8 magnitude earthquake struck with an epicenter located near Dahshur (Giza), about 35 km south of downtown Cairo.Why it was so deadly: Despite its moderate size, it became Egypt's deadliest modern seismic event, claiming over 560 lives, injuring more than 12,000 people, and leaving half a million homeless.The Cause: The earthquake occurred at a focal centroid depth of around 22~23 km. The high level of destruction was primarily caused by the shallow depth, the vulnerability of old adobe houses in poor neighborhoods, poorly maintained inner-city high-rises, and the unique soft soil of the Nile Valley, which amplified the seismic waves.Historic Impact: It caused notable damage to landmark historic Islamic monuments and mosques in Old Cairo, and even dislodged a large stone block from the Great Pyramid of Giza.",
        "short_tag": "I was near the surface so I killed many civilians",
    },
    {
        "id": "suez",
        "label": "Suez 2026",
        "magnitude": 5.6,
        # Suez city coords (used as epicenter in original)
        "epicenter_lon": 32.5498,
        "epicenter_lat": 29.9668,
        "story": "In the early morning hours of August 3, 2026, at approximately 3:00 AM local time, a 5.5 to 5.6 magnitude earthquake shook northern Egypt.The Location: The epicenter was located about 38 to 41 kilometers north-northeast of Suez (Latitude: 30.19° N, Longitude: 32.61° E). Because it struck while most people were asleep, the shaking caused a sudden wave of collective alarm and woke up residents across Cairo, Suez, Ismailia, Port Said, and Alexandria. It was even felt beyond Egypt's borders in Jordan, Israel, Palestine, and Lebanon.The Cause: The National Research Institute of Astronomy and Geophysics (NRIAG) reported that the tremor struck at a very shallow depth of 10 kilometers. It was triggered by localized crustal extension stretching along the northern Gulf of Suez and Red Sea rift fault lines.The Impact: Unlike 1992, no casualties or significant structural disasters were reported. Only minor structural incidents occurred, such as a collapsed balcony in Suez and a partial wall crack in Cairo. Modern building regulations and better reinforcement safety protocols implemented after 1992 successfully shielded the core populated zones from devastation.",
        "short_tag": "I was deep in earth that I didn't kill anyone",
    },
]
