# -*- coding: utf-8 -*-
"""simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gK2p5EeaPAV6wQ0Jqc8Mi1mHUn1WapWo
"""

# simulation.py

import random


# ==========================================
# 1. Simulate Crowd
# ==========================================

def simulate_crowd(places):

    # Loop through all tourist places
    for place in places:

        # Generate random number from 0 to 100
        crowd = random.randint(0, 100)

        # Store the crowd percentage
        places[place]["crowd"] = crowd

    # Return updated data
    return places


# ==========================================
# 2. Calculate Current Visitors
# ==========================================

def calculate_visitors(capacity, crowd):

    # Calculate number of current visitors
    visitors = capacity * crowd / 100

    # Return integer value
    return int(visitors)


# ==========================================
# 3. Determine Crowd Status
# ==========================================

def get_crowd_status(crowd):

    # Low crowd
    if crowd <= 30:
        return "Low"

    # Medium crowd
    elif crowd <= 70:
        return "Medium"

    # High crowd
    else:
        return "High"